server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true 
ribbon:
  eureka:
    enabled: true # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。
feign:
  hystrix:
    enabled: true
logging:
  all:
    level: info
  config: classpath:logback-spring.xml  
logstash:
  ip_port: 172.18.0.5:5000