version: "3.7"
services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    hostname: zipkin-server
    ports:
      - "9411:9411"
    depends_on:
      - elasticsearch
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: http://elasticsearch:9200
    networks:
      elk:
        aliases:
          - zipkin-server
      
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - elk
   
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      elk:
        aliases:
          - kafka
          
  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /opt/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    #  ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
 
  kibana:
    image: kibana:7.4.2
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    #volumes:
    #  - /opt/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
    depends_on:
      - elasticsearch
      
  logstash:
    image: logstash:7.4.2
    container_name: logstash
    hostname: logstash
    ports:
      - "5000:5000"
    volumes:
    #  - /opt/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /opt/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
     
networks:
  elk:
    name: elk
    driver: bridge 